services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/SudoR2spr/text-leech-bot
    branch: Koyeb-Render
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
